version: "3.4"
services:
    #PHP Service
    app:
        container_name: shopi-api-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./deployment/laravel/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - nodeye-backend
        depends_on:
            - pgsql

    #Nginx Service
    webserver:
        container_name: shopi-api-webserver
        image: nginx:1.17-alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - nodeye-backend

    # Database
    pgsql:
        container_name: shopi-api-pgsql
        image: "postgres:14"
        ports:
            - "5432:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - pgsql:/var/lib/postgresql/data
        networks:
            - nodeye-backend
networks:
    nodeye-backend:
        driver: bridge
volumes:
    pgsql:
        driver: local
